updated careers md, pulled in copy from notion
shapeshift/docs pull request #25
Opened 2022-03-07 20:35 UTC by 0xRowdy

2022-03-07 22:43 UTC, 0xApotheosis requested changes
A few suggestions. Also, I know it's not explicitly noted anywhere that we do it this way  but for markdown docs, could you please add a new line after each heading?

2022-03-07 22:43 UTC, 0xApotheosis commented on careers.md
> +- Join our standups at 10AM MST Mon-Fri in the StandUp-AllAccess channel on our [Discord](https://discord.gg/shapeshift) server
```suggestion
- Join our standups at 10AM MST Mon-Fri in the `StandUp-AllAccess` channel on our [Discord](https://discord.gg/shapeshift) server
```

2022-03-07 22:43 UTC, 0xApotheosis commented on careers.md
> +     - Once you are on the server and see a bunch of channels, go to the #role-selector channel, and click on the icon for the "Engineering" role
```suggestion
     - Once you are on the server and see a bunch of channels, go to the `#role-selector` channel, and click on the icon for the "Engineering" role
```

2022-03-07 22:43 UTC, 0xApotheosis commented on careers.md
> +     - Then you will see the #StandUp-AllAccess channel, #engineering-public channel and many others
```suggestion
     - Then you will see the `#StandUp-AllAccess` channel, `#engineering-public` channel and many others
```

2022-03-07 22:43 UTC, 0xApotheosis commented on careers.md
> +- Join the conversation and ask questions in the engineering-public channel on Discord
```suggestion
- Join the conversation and ask questions in the `#engineering-public` channel on Discord
```

2022-03-08 00:43 UTC, 0xRowdy commented
> A few suggestions. Also, I know it's not explicitly noted anywhere that we do it this way but for markdown docs, could you please add a new line after each heading?

Absolutely, I wanted to get some eyes on this PR before I start submitting others so I can get all of these kinds of comments resolved before submitting others. Thanks for the feedback!

2022-03-08 15:22 UTC, 0xApotheosis approved these changes

2022-03-08 15:23 UTC, 0xApotheosis commented
Nice one, thanks for making our docs cleaner!

2022-03-08 15:23 UTC, merged